ALTER TABLE project.traveler 
CHANGE COLUMN InputID InputID INT NOT NULL ,
CHANGE COLUMN Traveler_ID Traveler_ID INT NOT NULL ,
ADD PRIMARY KEY (InputID),
ADD UNIQUE INDEX InputID_UNIQUE (InputID ASC) VISIBLE;
;

ALTER TABLE project.country 
CHANGE COLUMN Traveler_Location Traveler_Location VARCHAR(200) NOT NULL ,
ADD PRIMARY KEY (Traveler_Location),
ADD UNIQUE INDEX Traveler_Location_UNIQUE (Traveler_Location ASC) VISIBLE;
;

ALTER TABLE project.date 
CHANGE COLUMN InputID InputID INT NOT NULL ,
CHANGE COLUMN Traveler_ID Traveler_ID INT NOT NULL ,
ADD PRIMARY KEY (InputID),
ADD UNIQUE INDEX InputID_UNIQUE (InputID ASC) VISIBLE;
;

ALTER TABLE project.location 
CHANGE COLUMN InputID InputID INT NOT NULL ,
CHANGE COLUMN Traveler_ID Traveler_ID INT NOT NULL ,
ADD PRIMARY KEY (InputID),
ADD UNIQUE INDEX InputID_UNIQUE (InputID ASC) VISIBLE;
;

ALTER TABLE project.type 
CHANGE COLUMN InputID InputID INT NOT NULL ,
CHANGE COLUMN Traveler_ID Traveler_ID INT NOT NULL ,
ADD PRIMARY KEY (InputID),
ADD UNIQUE INDEX InputID_UNIQUE (InputID ASC) VISIBLE;
;

ALTER TABLE project.comments 
CHANGE COLUMN InputID InputID INT NOT NULL ,
CHANGE COLUMN Traveler_ID Traveler_ID INT NOT NULL ,
ADD PRIMARY KEY (InputID),
ADD UNIQUE INDEX InputID_UNIQUE (InputID ASC) VISIBLE;
;



ALTER TABLE project.rating 
CHANGE COLUMN InputID InputID INT NOT NULL ,
CHANGE COLUMN Traveler_ID Traveler_ID INT NOT NULL ,
ADD UNIQUE INDEX InputID_UNIQUE (InputID ASC) VISIBLE,
ADD PRIMARY KEY (InputID);
;




ALTER TABLE project.votes 
CHANGE COLUMN InputID InputID INT NOT NULL ,
CHANGE COLUMN Traveler_ID Traveler_ID INT NOT NULL ,
ADD PRIMARY KEY (InputID),
ADD UNIQUE INDEX InputID_UNIQUE (InputID ASC) VISIBLE;
;
